repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0-1
  hooks:
  - id: fix-encoding-pragma
  - id: autopep8-wrapper
    args:
    - --in-place
    - --ignore=E501,E228,E226,E261,E266,E128,E402,E241
  - id: check-ast
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  # - id: check-docstring-first
  # - id: check-added-large-files
  # - id: debug-statements
  # - id: detect-private-key
  - id: flake8
    args:
    - --ignore=E501,E228,E226,E261,E266,E128,E402,W503,E722,F401
    - --builtins=G,request
    - --jobs=1
  # - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: requirements-txt-fixer
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.0
  hooks:
  - id: reorder-python-imports
